Products
wecode-bootcamp-korea/50-2nd-ORONAMIN_C-backend pull request #12
Opened 2023-11-01 03:18 UTC by juhyunju

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
회의 내용을 토대로 관리자 페이지 내에서 관리자가 상품을 조회,등록,수정,삭제 할 수 있도록 개발했습니다.

  (예시) 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 input 창 바로 아래에서 실시간으로 적색의 경고 메세지를 전달 받습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
관리자가 상품에 대한 CRUD를 할 수 있습니다. 

  (예시) 유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

(예시) 로그인 기능 추가

- (예시) email입력 `@`필요,password에 숫자로 8자이상 유효성 검사 추가
- (예시) 유효성 검사 통과시 버튼 컬러 변경 및 버튼 활성화

- 상품에 대한 CRUD
- 생성,수정,삭제를 할 때 관리자 계정임을 인증 받고 해당 API  실행
-  상품에 대한 조회는 쿼리 파라미터로 값을 전달 받도록 API 구현
-  상품을 조회할 때 반복적으로 나오는 향에 대한 설명은 최초의 한번만 나올 수 있게 구현
-  없는 상품을 조회할 경우 ERROR 발생
-  생성할 때 누락된 KEY값이 있을경우 KEY ERROR 를 반환
-  수정할 때 관리자가 수정하고 싶은 항목만 수정할 수 있도록 함수를 추가해서 API 구현

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />
<img width="913" alt="스크린샷 2023-11-01 오후 12 16 46" src="https://github.com/wecode-bootcamp-korea/50-2nd-ORONAMIN_C-backend/assets/73158866/cb3ff4b8-b354-4bb4-878b-a8a7ecf88765">

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- (예시) 새로운 배열메서드 filter를 쓸 수 있게됐습니다.
- (예시) 상수데이터와 map 메서드로 반복되는 UI를 그릴 수 있게 됐습니다.
- (예시) fetch함수를 어떻게 쓰는지 알게됐습니다.
- (예시) 계산된 속성명 (computed property)을 쓰긴했는데 어떻게 돌아가는지 이해가 잘 안되서
  블로그에 정리해봐야겠습니다.
- (예시) 화살표 함수(arrow-function) 어떤 코드를 언제 생략할 수있는지 완벽 이해했습니다.
- (예시) 구조분해할당(Destructuring assignment)을 써보니 가독성도, 유지보수도 편할것같습니다.
  <br />

-  좋은 경험이 되었습니다.

2023-11-01 04:58 UTC, soheon-lee reviewed
마이너한 업데이트 사항 몇 개만 수정해 주세요 :)

2023-11-01 04:58 UTC, soheon-lee commented on routes/productRouter.js
> +router.post('/create',productController.createProduct)
```suggestion
router.post('/',productController.createProduct)
```
- `[POST]` 라는 http method만으로도 데이터를 추가한다는 의미가 통하기 때문에 이용하지 않으셔도 됩니다!

2023-11-01 04:58 UTC, soheon-lee commented on services/productService.js
> +
```suggestion
    const getProduct = await productDao.getProduct(id)
    
    if(getProduct.length === 0){
        const err = new Error()
        err.statusCode = 400
        err.message = "없는 상품입니다."
        throw err;
    }
    
    const product = await productDao.updateProduct(productId,productName,price,description,brandId,scentId)
    return product 

```
- product 업데이트를 하기 전에 product 존재 여부를 확인하는 로직이 먼저 오는 것이 맥락상 좋을 것 같습니다!

2023-11-01 08:29 UTC, soheon-lee requested changes
확인 부탁드립니다 :)

2023-11-01 08:29 UTC, soheon-lee commented on controller/productController.js
> +            return res.status(400).json({message: "INPUT_KEY_ERROR"})
여기서도 에러가 return 되고 있네요, API 하나만 바꾸지 마시고, 전체 API들 전면 확인하셔서 이렇게 error return 하고 있는 부분은 전부 throw로 바꿔주세요~

2023-11-01 08:29 UTC, soheon-lee commented on controller/productController.js
> +        console.log(products[0].scent_desc)
불필요한 콘솔로그 전면 재확인 하셔서 모두 삭제해 주세요

2023-11-01 08:29 UTC, soheon-lee commented on controller/productController.js
> +        res.status(200).json(products)
```suggestion
        res.status(200).json({ products })
```

데이터 그냥 배열로 보내시면 안되고 객체 형태로 보내셔야 합니다. key-value 형태로 변경해 주세요!

2023-11-01 08:29 UTC, soheon-lee commented on controller/productController.js
> +
생성되는 에러를 모두 500으로 보내나요? throw해서 받는 에러의 status code가 필요할 것 같습니다

2023-11-01 08:29 UTC, soheon-lee commented on controller/productController.js
> +                res.status(200).json({message: "등록완료~!"})
메세지 형식 통일해 주세요. 팀에 컨벤션 만드셔서 통일하시는게 좋을 것 같습니다.

2023-11-02 02:57 UTC, soheon-lee reviewed
마지막 리뷰 확인하시고 머지할게요!

2023-11-02 02:57 UTC, soheon-lee commented on controller/productController.js
> +    }catch(err){
```suggestion
        if(token){
            const userType = {
              ADMIN : 1
            }
            if(decodedToken.status === userType.ADMIN){
                await productService.updateProduct(productId,productName,price,description,brandId,scentId,imageId)
                res.status(200).json({message: "successfully updated"})
            }else{
                throw new Error("Permission Denied")
            }
        }
    }catch(err){
```
1. 에러 statusCode가 없어요, 추가해 주세요 :)
2. decodedToken.status 1번이 어떤 상태인지 판단하기가 어렵습니다. 상위에 객체 하나 선언하셔서 어떤 상태인지 보다 명확히 해주세요

2023-11-02 03:35 UTC, soheon-lee commented
@juhyunju 컨플릭트 전면 수정해 주세요 ~

2023-11-02 05:14 UTC, soheon-lee reviewed
1. 로직엔 큰 변경 없고 전반적인 가독성 개선 작업이 필요합니다.
2. 코드 띄어쓰기가 기본 4칸인 것 같은데, JavaScript는 2칸 공백이 기본값입니다. 공백 전면 수정해주세요 :)

2023-11-02 05:14 UTC, soheon-lee commented on controller/productController.js
> +
```suggestion

const productAll = async(req,res) =>{
    try {
        const { brandName, scentName } = req.query
        const products = await productService.getProducts(brandName, scentName)
        
        return res.status(200).json({products})
    } catch(err) {
        res.status(statusCode || 500).json({ message: err.message })
    }
}

```
`500 || statusCode` 로 하면, 모든 에러가 100% 500으로 코드가 갑니다. 왜일까요?

2023-11-02 05:14 UTC, soheon-lee commented on controller/productController.js
> +
try -catch 띄어쓰기 간격이 없어요. 구문 앞뒤로 공백 한 칸씩 띄워주시고, 모든 파일에 전면 반영해 주세요 :)

2023-11-02 05:14 UTC, soheon-lee commented on models/productDao.js
> +    LEFT JOIN images ON products.image_id = images.id
SELECT하는 컬럼마다 한 줄씩 다 띄워주세요 :)

2023-11-02 05:14 UTC, soheon-lee commented on models/productDao.js
> +    LEFT JOIN images ON products.image_id = images.id
모든 SQL 코드에 전부 반영해 주세요

2023-11-02 05:43 UTC, juhyunju commented on controller/productController.js
> +
OR 조건 때문에 500이 들어오면 항상 true로 판단하기 때문에 500으로 코드가 나가는 것 같습니다.
소헌님이 말씀해주신 코드대로 변경을 하면 statusCode가 존재하면 해당 값이 사용되고 그렇지 않으면 500이 사용 되는것 같습니다..(?)

2023-11-02 08:18 UTC, soheon-lee approved these changes
LGTM-!

2023-11-02 08:18 UTC, merged